#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jzlib
Version  : 1.1.1
Release  : 1
URL      : https://github.com/ymnk/jzlib/archive/1.1.1.tar.gz
Source0  : https://github.com/ymnk/jzlib/archive/1.1.1.tar.gz
Source1  : https://repo1.maven.org/maven2/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.jar
Source2  : https://repo1.maven.org/maven2/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-jzlib-data = %{version}-%{release}

%description
JZlib
zlib in pure Java(TM)
by ymnk@jcraft.com, JCraft,Inc.
http://www.jcraft.com/jzlib/

%package data
Summary: data components for the mvn-jzlib package.
Group: Data

%description data
data components for the mvn-jzlib package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jzlib/1.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jzlib/1.1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jzlib/1.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jzlib/1.1.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.jar
/usr/share/java/.m2/repository/com/jcraft/jzlib/1.1.1/jzlib-1.1.1.pom
